name: Project 0 Testing only
on:
  pull_request:
  push:
    branches: 
      - master

jobs:
  test:
    name: Running Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Install
        run: npm install
      - name: Test
        run: npm test
